name: 自動提交和推送

on:
  workflow_dispatch:  # 手動觸發

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出代碼
      uses: actions/checkout@v6

    - name: 進行修改
      run: |
        echo "Update on $(date)" >> update
        # 你可以在這裡添加更多自動化變更的指令

    - name: 提交變更
      run: |
        git config --global user.email "th04e22@gmail.com"
        git config --global user.name "Terry Huang"
        git add .
        git commit -m "Automated commit on $(date)"
    
    - name: 推送代碼
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: git push origin main